BlowOut/BlowOut/Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BlowOut.DAL;
using BlowOut.Models;

namespace BlowOut.Controllers
{
    public class ClientsController : Controller
    {
        private BlowoutContext db = new BlowoutContext();

        // GET: Clients
        public ActionResult Index()
        {
            return View(db.Clients.ToList());
        }

        // GET: Clients/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // GET: Clients/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Clients/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "clientID,firstName,lastName,address,city,state,zip,email,phone")] Client client)
        {
            if (ModelState.IsValid)
            {
                db.Clients.Add(client);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(client);
        }

        // GET: Clients/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // POST: Clients/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "clientID,firstName,lastName,address,city,state,zip,email,phone")] Client client)
        {
            if (ModelState.IsValid)
            {
                db.Entry(client).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(client);
        }

        // GET: Clients/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // POST: Clients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Client client = db.Clients.Find(id);
            db.Clients.Remove(client);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BlowOut/BlowOut/Controllers/RentalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BlowOut.Models;

namespace BlowOut.Controllers
{
    public class RentalsController : Controller
    {

        // GET: Rentals
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Trumpet(string price)
        {
            ViewBag.value = price;
            return View();
        }

        public ActionResult Trombone(string price)
        {
            ViewBag.value = price;
            return View();
        }

        public ActionResult Tuba(string price)
        {
            ViewBag.value = price;
            return View();
        }

        public ActionResult Flute(string price)
        {
            ViewBag.value = price;
            return View();
        }

        public ActionResult Clarinet(string price)
        {
            ViewBag.value = price;
            return View();
        }

        public ActionResult Saxaphone(string price)
        {
            ViewBag.value = price;
            return View();
        }
    }
}

BlowOut/BlowOut/Views/Rentals/Clarinet.cshtml
@{
    ViewBag.Title = "Clarinet";
}

<head>
    <link rel="stylesheet" href="~/Content/Site.css">
</head>
<h2><b>Clarinet</b></h2>
<div class="row">
    <div class="columnInstrument">
        <img src="~/Content/Images/clarinet.jpg" alt="Trumpet" />
        <p>@Html.ActionLink("New", "Clarinet", "Rentals", new { price = "New - $35 a month" }, new { @class = "btn btn-primary btn-large" })</p>
        <p>@Html.ActionLink("Used", "Clarinet", "Rentals", new { price = "Used - $27 a month" }, new { @class = "btn btn-primary btn-large" })</p>
        <p>@ViewBag.value</p>
    </div>
</div>
<p style="font-size:small">
    Once the 18 months has been achieved, the client owns the instrument. If they return it at any time before 3 months there
    will be a $200 re-stocking fee. If they return it after 3 months they forfeit any equity in the instrument.
</p>

BlowOut/BlowOut/Views/Rentals/Flute.cshtml
@{
    ViewBag.Title = "Flute";
}

<head>
    <link rel="stylesheet" href="~/Content/Site.css">
</head>
<h2><b>Flute</b></h2>
<div class="row">
    <div class="columnInstrument">
        <img src="~/Content/Images/flute.jpg" alt="Trumpet" />
        <p>@Html.ActionLink("New", "Flute", "Rentals", new { price = "New - $40 a month" }, new { @class = "btn btn-primary btn-large" })</p>
        <p>@Html.ActionLink("Used", "Flute", "Rentals", new { price = "Used - $25 a month" }, new { @class = "btn btn-primary btn-large" })</p>
        <p>@ViewBag.value</p>
    </div>
</div>
<p style="font-size:small">
    Once the 18 months has been achieved, the client owns the instrument. If they return it at any time before 3 months there
    will be a $200 re-stocking fee. If they return it after 3 months they forfeit any equity in the instrument.
</p>

BlowOut/BlowOut/Views/Rentals/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<head>
    <link rel="stylesheet" href="~/Content/Site.css">
</head>
<h2>Rental Options</h2>
<div class="row">
    <a href="@Url.Action("Create", "Clients")">
        <img src="~/Content/Images/trumpet.jpg" alt="Trumpet" class="column" />
    </a>
    <a href="@Url.Action("Trombone", "Rentals")">
        <img src="~/Content/Images/trombone.jpg" alt="Trombone" class="column" />
    </a>
    <a href="@Url.Action("Tuba", "Rentals")">
        <img src="~/Content/Images/tuba.jpg" alt="Tuba" class="column" />
    </a>
</div>
<div class="row">
    <a href="@Url.Action("Flute", "Rentals")">
        <img src="~/Content/Images/flute.jpg" alt="Flute" class="column" />
    </a>
    <a href="@Url.Action("Clarinet", "Rentals")">
        <img src="~/Content/Images/clarinet.jpg" alt="Clarinet" class="column" />
    </a>
    <a href="@Url.Action("Saxaphone", "Rentals")">
        <img src="~/Content/Images/saxophone.jpg" alt="Saxaphone" class="column" />
    </a>
</div>

BlowOut/BlowOut/Views/Rentals/Saxaphone.cshtml
@{
    ViewBag.Title = "Saxaphone";
}

<head>
    <link rel="stylesheet" href="~/Content/Site.css">
</head>
<h2><b>Saxophone</b></h2>
<div class="row">
    <div class="columnInstrument">
        <img src="~/Content/Images/saxophone.jpg" alt="Trumpet" />
        <p>@Html.ActionLink("New", "Saxaphone", "Rentals", new { price = "New - $42 a month" }, new { @class = "btn btn-primary btn-large" })</p>
        <p>@Html.ActionLink("Used", "Saxaphone", "Rentals", new { price = "Used - $30 a month" }, new { @class = "btn btn-primary btn-large" })</p>
        <p>@ViewBag.value</p>
    </div>
</div>
<p style="font-size:small">
    Once the 18 months has been achieved, the client owns the instrument. If they return it at any time before 3 months there
    will be a $200 re-stocking fee. If they return it after 3 months they forfeit any equity in the instrument.
</p>

BlowOut/BlowOut/Views/Rentals/Trombone.cshtml
@{
    ViewBag.Title = "Trombone";
}

<head>
    <link rel="stylesheet" href="~/Content/Site.css">
</head>
<h2><b>Trombone</b></h2>
<div class="row">
    <div class="columnInstrument">
        <img src="~/Content/Images/trombone.jpg" alt="Trumpet" />
        <p>@Html.ActionLink("New", "Trombone", "Rentals", new { price = "New - $60 a month" }, new { @class = "btn btn-primary btn-large" })</p>
        <p>@Html.ActionLink("Used", "Trombone", "Rentals", new { price = "Used - $35 a month" }, new { @class = "btn btn-primary btn-large" })</p>
        <p>@ViewBag.value</p>
    </div>
</div>
<p style="font-size:small">
    Once the 18 months has been achieved, the client owns the instrument. If they return it at any time before 3 months there
    will be a $200 re-stocking fee. If they return it after 3 months they forfeit any equity in the instrument.
</p>

BlowOut/BlowOut/Views/Rentals/Trumpet.cshtml
@{
    /**/

    ViewBag.Title = "Trumpet";
}

<head>
    <link rel="stylesheet" href="~/Content/Site.css">
</head>
<h2><b>Trumpet</b></h2>
<div class="row">
    <div class="columnInstrument">
        <img src="~/Content/Images/trumpet.jpg" alt="Trumpet" />
        <p>@Html.ActionLink("New", "Trumpet", "Rentals", new { price = "New - $55 a month" }, new { @class = "btn btn-primary btn-large" })</p>
        <p>@Html.ActionLink("Used", "Trumpet", "Rentals", new { price = "Used - $25 a month" }, new { @class = "btn btn-primary btn-large" })</p>
        <p>@ViewBag.value</p>
    </div>
</div>
<p style="font-size:small">
    Once the 18 months has been achieved, the client owns the instrument. If they return it at any time before 3 months there
    will be a $200 re-stocking fee. If they return it after 3 months they forfeit any equity in the instrument.
</p>

BlowOut/BlowOut/Views/Rentals/Tuba.cshtml
@{
    ViewBag.Title = "Tuba";
}

<head>
    <link rel="stylesheet" href="~/Content/Site.css">
</head>
<h2><b>Tuba</b></h2>
<div class="row">
    <div class="columnInstrument">
        <img src="~/Content/Images/tuba.jpg" alt="Trumpet" />
        <p>@Html.ActionLink("New", "Tuba", "Rentals", new { price = "New - $70 a month" }, new { @class = "btn btn-primary btn-large" })</p>
        <p>@Html.ActionLink("Used", "Tuba", "Rentals", new { price = "Used - $50 a month" }, new { @class = "btn btn-primary btn-large" })</p>
        <p>@ViewBag.value</p>
    </div>
</div>
<p style="font-size:small">
    Once the 18 months has been achieved, the client owns the instrument. If they return it at any time before 3 months there
    will be a $200 re-stocking fee. If they return it after 3 months they forfeit any equity in the instrument.
</p>